In [54]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

food_data = pd.read_csv('food_data.csv')
food_data.head()
food_data.info()
food_data.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Food                   61 non-null     object
 1   Calories               61 non-null     int64
 2   Calories from Fat      61 non-null     int64
 3   Total Fat              61 non-null     float64
 4   Total Fat.1            61 non-null     int64
 5   Sodium                 61 non-null     int64
 6   Sodium.1               61 non-null     int64
 7   Potassium              61 non-null     int64
 8   Potassium.1            61 non-null     int64
 9   Total Carbo-hydrate    61 non-null     int64
 10  Total Carbo-hydrate.1  61 non-null     int64
 11  Protein                61 non-null     int64
 12  Vitamin A              61 non-null     int64
 13  Vitamin C              61 non-null     int64
 14  Calcium                61 non-null     int64
 15  Iron                   61 non-null     int64
 16  Food Type              61 non-null     object
dtypes: float64(1), int64(14), object(2)
memory usage: 8.2+ KB

,Food,Calories,Calories from Fat,Total Fat,Total Fat.1,Sodium,Sodium.1,Potassium,Potassium.1,Total Carbo-hydrate,Total Carbo-hydrate.1,Protein,Vitamin A,Vitamin C,Calcium,Iron,Food Type
56,Scallops,140,10,1.0,2,310,13,430,12,5,2,27,2,0,4,14,Seafood
57,Shrimp,100,10,1.5,2,240,10,220,6,0,0,21,4,4,6,10,Seafood
58,Swordfish,120,50,6.0,9,100,4,310,9,0,0,16,2,2,0,6,Seafood
59,Tilapia,110,20,2.5,4,30,1,360,10,0,0,22,0,2,0,2,Seafood
60,Tuna,130,15,1.5,2,40,2,480,14,0,0,26,2,2,2,4,Seafood

In [ ]:
# selecting the dependent and independent variables
food_data.index = food_data.iloc[:, 0]
x = food_data.iloc[:, 1:16]
y = food_data.iloc[:, 16]

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state=420)

gnb = GaussianNB()
gnb.fit(x_train,y_train)
y_pred_gnb = gnb.predict(x_test)

db = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_gnb})

db

metrics.accuracy_score(y_test, y_pred_gnb)

0.9230769230769231

In [65]:
candy_data = pd.read_csv('candy-data.csv')
candy_data.head()

# select the dependent and independent variables
x = candy_data.iloc[:, 10:13]
y = candy_data.iloc[:, 1]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 52)

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)
y_pred_log = log_reg.predict(x_test)

db = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_log})

metrics.accuracy_score(y_test,y_pred_log)

0.8461538461538461